name: GitHub Actions Demo
on:
  push:
    branches: [master]

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Read .nvmrc into variable
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm

      - name: Use Node Version in .nvmrc
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: NPM Clean Install
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: azure-func-test
          package: dist
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

      - name: Check if function is up
        run: curl https://azure-func-test.azurewebsites.net/api/httpfunc
          